export const API_SERVER_URL = import.meta.env.VITE_API_SERVER_URL;
export const prefixs = [
  { prefix: "y", name: "욕토", exponent: -24 },
  { prefix: "z", name: "젭토", exponent: -21 },
  { prefix: "a", name: "아토", exponent: -18 },
  { prefix: "f", name: "펨토", exponent: -15 },
  { prefix: "p", name: "피코", exponent: -12 },
  { prefix: "n", name: "나노", exponent: -9 },
  { prefix: "µ", name: "마이크로", exponent: -6 },
  { prefix: "m", name: "밀리", exponent: -3 },
  { prefix: "c", name: "센티", exponent: -2 },
  { prefix: "d", name: "데시", exponent: -1 },
  { prefix: "", name: "", exponent: 0 },
  { prefix: "da", name: "데카", exponent: 1 },
  { prefix: "h", name: "헥토", exponent: 2 },
  { prefix: "k", name: "킬로", exponent: 3 },
  { prefix: "M", name: "메가", exponent: 6 },
  { prefix: "G", name: "기가", exponent: 9 },
  { prefix: "T", name: "테라", exponent: 12 },
  { prefix: "P", name: "페타", exponent: 15 },
  { prefix: "E", name: "엑사", exponent: 18 },
  { prefix: "Z", name: "제타", exponent: 21 },
  { prefix: "Y", name: "요타", exponent: 24 },
];